FROM prefecthq/prefect:2.7.10-python3.9

COPY docker_requirements.txt .

RUN pip install -r docker_requirements.txt --trusted-host pypi.python.org --no-cache-dir

COPY data /opt/prefect/data

RUN mkdir -p /opt/prefect/data/yellow